# Generated by Django 3.1.3 on 2020-12-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201209_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/users/default.jpg', upload_to='users'),
        ),
    ]
