# Generated by Django 3.1.3 on 2020-11-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0004_auto_20201108_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
