# Generated by Django 3.1.3 on 2020-11-08 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0005_auto_20201108_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
