# Generated by Django 3.1.3 on 2020-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0006_auto_20201108_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Bulgarian', 'Worldwide')], default='Bulgarian', max_length=30),
        ),
    ]
