# Generated by Django 3.1.3 on 2020-11-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0007_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Worldwide', 'Worldwide'), ('Bulgarian', 'Bulgarian')], default='Bulgarian', max_length=30),
        ),
    ]
