# Generated by Django 3.1.3 on 2020-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0010_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='boza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_needed',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Worldwide', 'Worldwide'), ('Bulgarian', 'Bulgarian'), ('Asian', 'Asian'), ('Thai', 'Thai'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Italian', 'Italian')], default='Bulgarian', max_length=30),
        ),
    ]
