# Generated by Django 3.1.3 on 2020-12-12 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepiesSite', '0011_auto_20201119_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
