# Generated by Django 3.1.3 on 2020-12-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201212_0930'),
        ('RecepiesSite', '0012_auto_20201212_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
